### ISSUE TITLE
Fix memory leak when using zenity

### ISSUE THREAD

**Issue by freebsdfrau** [FrauBSD/pkgcenter#2]
The introduction of "if (!use_zenity)" causes a memory leak when using zenity.

https://github.com/FrauBSD/pkgcenter/blob/c64aa1346c9b79e8f39b85a0f3880838da45ead2/depend/libdpv/dialog_util.c#L324-L325

That's because when using zenity, this line allocates 8 bytes indiscriminately:

https://github.com/FrauBSD/pkgcenter/blob/c64aa1346c9b79e8f39b85a0f3880838da45ead2/depend/libdpv/dialog_util.c#L322

And when using zenity, we do not populate the allocate memory (at line 325), but instead replace the pointer with a different pointer at this line:

https://github.com/FrauBSD/pkgcenter/blob/c64aa1346c9b79e8f39b85a0f3880838da45ead2/depend/libdpv/dialog_util.c#L326

So the pointer returned by malloc on line 322 is lost (we no longer have the value) which equates to leaked memory (it can never be freed because we don't have the pointer).

The "if !use_zenity" condition should encompass the malloc at line 322 (just move lines 322 and 323 down, above line 325, putting the malloc and errx inside the condition currently at line 324, add curlies to the condition and indent as-needed.

**Comment by freebsdfrau** [comment]
Can we combine the two if-statements by using an "} else {" instead of starting a new if-statement here?

https://github.com/FrauBSD/pkgcenter/blob/5347254f13c97c230a26977aa5e421b0cfe9a591/depend/libdpv/dialog_util.c#L332-L333

**Comment by freebsdfrau** [comment]
While we're here can we combine the if-statements above it, changing to "} else if (use_zenity) {" at:

https://github.com/FrauBSD/pkgcenter/blob/5347254f13c97c230a26977aa5e421b0cfe9a591/depend/libdpv/dialog_util.c#L315-L316

**Comment by freebsdfrau** [comment]
Taken care of.

**Comment by kfv** [comment]
My apologies, I didn't receive the notification. I just took care of my email notification preferences to ensure I won't miss anything again.
